apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:2.8.2
          args:
            - -config.file=/etc/loki/loki-config.yaml
          ports:
            - containerPort: 3100
            - containerPort: 9096
          volumeMounts:
            - name: config-volume
              mountPath: /etc/loki
            - name: data-volume
              mountPath: /loki
      volumes:
        - name: config-volume
          configMap:
            name: loki-config
        - name: data-volume
          emptyDir: {}  # This will create an empty directory for data storage (use PersistentVolume in production)
