apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: loki
spec:
  type: NodePort
  ports:
    - port: 3100
      targetPort: 3100
      nodePort: 30000  # Specify your desired NodePort
  selector:
    app: loki
