auth_enabled: false

server:
  http:
    port: 3100
  grpc:
    port: 9095

ingester:
  wal:
    enabled: true
    dir: /loki/wal

  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_chunk_size: 1048576
  min_chunk_size: 32768

storage_config:
  boltdb:
    directory: /loki/chunks

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 168h  # Keep indices for one week
