apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: 1000  # Ensure the group ownership of mounted volumes is correct
      containers:
        - name: loki
          image: grafana/loki:2.8.2
          args:
            - "-config.file=/etc/loki/loki-config.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/loki
            - name: data-volume
              mountPath: /loki
          securityContext:
            runAsUser: 1000  # Ensure the Loki container runs as user 1000
      volumes:
        - name: config-volume
          configMap:
            name: loki-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: loki-pvc  # Or use a hostPath volume
---
apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
      nodePort: 31483 
  type: NodePort
