# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: promtail-config
#   namespace: promtail
# data:
#   promtail.yaml: |
#     server:
#       http_listen_port: 9080
#       grpc_listen_port: 0

#     positions:
#       filename: /tmp/positions.yaml

#     clients:
#       - url: http://loki:3100/loki/api/v1/push

#     scrape_configs:
#       - job_name: kubernetes-pods
#         kubernetes_sd_configs:
#           - role: pod
#         relabel_configs:
#           - source_labels: [__meta_kubernetes_pod_label_app]
#             target_label: job
#           - source_labels: [__meta_kubernetes_pod_name]
#             target_label: pod_name
#           - source_labels: [__meta_kubernetes_namespace]
#             target_label: namespace
#             # No regex filter here to include all namespaces
#           - source_labels: [__meta_kubernetes_pod_container_name]
#             target_label: container
#           - action: replace
#             source_labels: [__meta_kubernetes_pod_container_name]
#             target_label: __path__
#             replacement: /var/log/containers/*${__meta_kubernetes_pod_name}_${__meta_kubernetes_namespace}_${__meta_kubernetes_pod_container_name}.log



apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: promtail
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod_name
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - action: replace
            source_labels: [__meta_kubernetes_pod_container_name]
            target_label: __path__
            replacement: /var/log/pods/*/*.log


