apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail  
      containers:
        - name: promtail
          image: grafana/promtail:2.8.2
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/promtail
            - name: positions
              mountPath: /tmp
      volumes:
        - name: config-volume
          configMap:
            name: promtail-config
        - name: positions
          emptyDir: {}
