# kind: Cluster
# apiVersion: kind.x-k8s.io/v1alpha4
# networking:
#   kubeProxyMode: ipvs
# nodes:
#   - role: control-plane
#     extraPortMappings:
#       - containerPort: 80
#         hostPort: 30080
#         protocol: TCP
#       - containerPort: 443
#         hostPort: 30081
#         protocol: TCP
#   - role: worker
#     extraPortMappings:
#       - containerPort: 80
#         hostPort: 30082
#         protocol: TCP
#       - containerPort: 443
#         hostPort: 30083
#         protocol: TCP
#   - role: worker
#     extraPortMappings:
#       - containerPort: 80
#         hostPort: 30084
#         protocol: TCP
#       - containerPort: 443
#         hostPort: 30085
#         protocol: TCP
#   - role: worker
#     extraPortMappings:
#       - containerPort: 80
#         hostPort: 30086
#         protocol: TCP
#       - containerPort: 443
#         hostPort: 30087
#         protocol: TCP


kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: logshipping
networking:
  kubeProxyMode: ipvs
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 40080  # Changed port
        protocol: TCP
      - containerPort: 443
        hostPort: 40081  # Changed port
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 80
        hostPort: 40082  # Changed port
        protocol: TCP
      - containerPort: 443
        hostPort: 40083  # Changed port
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 80
        hostPort: 40084  # Changed port
        protocol: TCP
      - containerPort: 443
        hostPort: 40085  # Changed port
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 80
        hostPort: 40086  # Changed port
        protocol: TCP
      - containerPort: 443
        hostPort: 40087  # Changed port
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 80
        hostPort: 40088  # Changed port
        protocol: TCP
      - containerPort: 443
        hostPort: 40089  # Changed port
        protocol: TCP
