kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  kubeProxyMode: ipvs
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 30080
        protocol: TCP
      - containerPort: 443
        hostPort: 30081
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 80
        hostPort: 30082
        protocol: TCP
      - containerPort: 443
        hostPort: 30083
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 80
        hostPort: 30084
        protocol: TCP
      - containerPort: 443
        hostPort: 30085
        protocol: TCP
  - role: worker
    extraPortMappings:
      - containerPort: 80
        hostPort: 30086
        protocol: TCP
      - containerPort: 443
        hostPort: 30087
        protocol: TCP
